"use client";

import React, { useState, useEffect } from "react";
import Link from "next/link";

export interface NotificationItem {
  id: string;
  type: "critical" | "operational" | "patient" | "ot" | "cssd" | "system";
  title: string;
  description: string;
  department: string;
  timestamp: string;
  read: boolean;
  actionText: string;
  actionHref: string;
  entityId?: string;
  timeline?: { time: string; event: string }[];
}

const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "NOTIF-001",
    type: "critical",
    title: "Critical Alert: Sterile Pack Expiry",
    description: "Sterile Pack GEN-SET-09 has reached expiration date in active OT inventory holding.",
    department: "CSSD",
    timestamp: "11:50 AM",
    read: false,
    actionText: "View Alert",
    actionHref: "/alerts",
    entityId: "ALT-002",
    timeline: [
      { time: "11:50 AM", event: "Notification generated by CSSD Lead Expiry Monitor" },
      { time: "11:52 AM", event: "Routed to CSSD Supervisor & Duty Administrator" },
    ],
  },
  {
    id: "NOTIF-002",
    type: "ot",
    title: "OT Schedule Update",
    description: "OT 1 procedure 'Laparoscopic Cholecystectomy' has entered in-procedure stage.",
    department: "Operating Theatre",
    timestamp: "11:20 AM",
    read: false,
    actionText: "View Schedule",
    actionHref: "/ot-dashboard",
    entityId: "PROC-5001",
    timeline: [
      { time: "11:20 AM", event: "Procedure status changed to In-Procedure" },
    ],
  },
  {
    id: "NOTIF-003",
    type: "patient",
    title: "Patient Transfer Requested",
    description: "Transfer requested for patient Wei Chen (PT-10482) from ICU Bed 04 to Ward A.",
    department: "General Wards",
    timestamp: "10:40 AM",
    read: false,
    actionText: "View Patient",
    actionHref: "/patients",
    entityId: "PT-10482",
    timeline: [
      { time: "10:40 AM", event: "Transfer request dispatched by ICU Duty Physician" },
    ],
  },
  {
    id: "NOTIF-004",
    type: "patient",
    title: "New Patient Admission",
    description: "Ravi Deshmukh admitted to Ward A Bed 04. Vitals intake baseline completed.",
    department: "Admissions",
    timestamp: "09:45 AM",
    read: true,
    actionText: "View Patient",
    actionHref: "/patients",
    entityId: "PT-10499",
    timeline: [
      { time: "09:45 AM", event: "Admission record registered by Intake Desk" },
    ],
  },
  {
    id: "NOTIF-005",
    type: "critical",
    title: "ICU Ventilator Telemetry Alert",
    description: "Ventilator Unit #V-04 recorded flow pressure variance exceeding warning threshold.",
    department: "Emergency",
    timestamp: "12:35 PM",
    read: false,
    actionText: "View Alert",
    actionHref: "/alerts",
    entityId: "ALT-006",
    timeline: [
      { time: "12:35 PM", event: "Telemetry alarm triggered by sensor #V-04" },
    ],
  },
  {
    id: "NOTIF-006",
    type: "system",
    title: "Security Policy Refreshed",
    description: "Mediflow-AI security policy matrix refreshed by System Administrator Dr. Anika Rao.",
    department: "Administration",
    timestamp: "08:30 AM",
    read: true,
    actionText: "View Security",
    actionHref: "/settings",
    entityId: "SEC-POL-901",
    timeline: [
      { time: "08:30 AM", event: "Security policy matrix updated" },
    ],
  },
  {
    id: "NOTIF-007",
    type: "ot",
    title: "OT Turnover Delay Flagged",
    description: "OT 02 turnover between cases exceeded baseline target by 12 minutes.",
    department: "Operating Theatre",
    timestamp: "07:45 AM",
    read: true,
    actionText: "View OT",
    actionHref: "/ot-dashboard",
    entityId: "ALT-001",
  },
  {
    id: "NOTIF-008",
    type: "operational",
    title: "Ward Capacity Threshold Warning",
    description: "Ward A bed occupancy reached 82% (39 of 48 beds occupied). High intake expected.",
    department: "General Wards",
    timestamp: "07:15 AM",
    read: true,
    actionText: "View Wards",
    actionHref: "/settings",
    entityId: "ALT-003",
  },
  {
    id: "NOTIF-009",
    type: "cssd",
    title: "Sterilization Cycle Completed",
    description: "Autoclave Chamber 1 completed Sterilization Cycle #B805 cleanly (0 anomalies).",
    department: "CSSD",
    timestamp: "06:30 AM",
    read: true,
    actionText: "View CSSD",
    actionHref: "/settings",
    entityId: "BATCH-9001",
  },
  {
    id: "NOTIF-010",
    type: "system",
    title: "Role Permissions Modified",
    description: "Permissions modified for role OT Manager by System Administrator.",
    department: "Administration",
    timestamp: "Yesterday",
    read: true,
    actionText: "View System",
    actionHref: "/settings",
    entityId: "USR-002",
  },
  {
    id: "NOTIF-011",
    type: "patient",
    title: "Laboratory Panel Intake Ready",
    description: "Blood panel & cardiac enzyme lab results uploaded for patient PT-10482.",
    department: "Admissions",
    timestamp: "Yesterday",
    read: true,
    actionText: "View Patient",
    actionHref: "/patients",
    entityId: "PT-10482",
  },
  {
    id: "NOTIF-012",
    type: "operational",
    title: "Shift Turnover Completed",
    description: "ICU Night Shift turnover report finalized and signed by Charge Nurse Elena Rostova.",
    department: "General Wards",
    timestamp: "Yesterday",
    read: true,
    actionText: "View Wards",
    actionHref: "/settings",
    entityId: "REP-DAILY-0811",
  },
];

export function NotificationsBoard() {
  const [notifications, setNotifications] = useState<NotificationItem[]>(INITIAL_NOTIFICATIONS);
  const [searchQuery, setSearchQuery] = useState("");
  const [typeFilter, setTypeFilter] = useState("all");
  const [statusFilter, setStatusFilter] = useState("all");
  const [timeFilter, setTimeFilter] = useState("today");

  // Pagination State
  const [currentPage, setCurrentPage] = useState(1);
  const [pageSize, setPageSize] = useState(10);

  // Detail Modal / Drawer State
  const [selectedNotif, setSelectedNotif] = useState<NotificationItem | null>(null);
  const [toastMessage, setToastMessage] = useState<string | null>(null);

  const showToast = (msg: string) => {
    setToastMessage(msg);
    setTimeout(() => setToastMessage(null), 3500);
  };

  // Keyboard Escape
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === "Escape") {
        setSelectedNotif(null);
      }
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  // Filter Logic
  const filteredNotifications = notifications.filter((item) => {
    const matchesSearch =
      item.title.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.description.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.department.toLowerCase().includes(searchQuery.toLowerCase()) ||
      item.id.toLowerCase().includes(searchQuery.toLowerCase());

    const matchesType = typeFilter === "all" || item.type === typeFilter;
    const matchesStatus =
      statusFilter === "all" ||
      (statusFilter === "unread" && !item.read) ||
      (statusFilter === "read" && item.read);

    return matchesSearch && matchesType && matchesStatus;
  });

  // KPI Calculations
  const unreadCount = notifications.filter((n) => !n.read).length;
  const criticalCount = notifications.filter((n) => n.type === "critical").length;
  const operationalCount = notifications.filter((n) => n.type === "operational" || n.type === "ot" || n.type === "cssd").length;
  const systemCount = notifications.filter((n) => n.type === "system").length;

  // Pagination Calculations
  const totalPages = Math.ceil(filteredNotifications.length / pageSize) || 1;
  const safeCurrentPage = Math.min(currentPage, totalPages);
  const startIndex = (safeCurrentPage - 1) * pageSize;
  const paginatedNotifications = filteredNotifications.slice(startIndex, startIndex + pageSize);

  // Handlers
  const handleMarkAllRead = () => {
    setNotifications((prev) => prev.map((n) => ({ ...n, read: true })));
    showToast("✓ All notifications marked as read.");
  };

  const handleToggleRead = (id: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setNotifications((prev) =>
      prev.map((n) => (n.id === id ? { ...n, read: !n.read } : n))
    );
    if (selectedNotif && selectedNotif.id === id) {
      setSelectedNotif((prev) => (prev ? { ...prev, read: !prev.read } : null));
    }
  };

  const handleDeleteNotif = (id: string, e?: React.MouseEvent) => {
    if (e) e.stopPropagation();
    setNotifications((prev) => prev.filter((n) => n.id !== id));
    if (selectedNotif && selectedNotif.id === id) {
      setSelectedNotif(null);
    }
    showToast("Notification item removed.");
  };

  const handleOpenDetail = (notif: NotificationItem) => {
    // Mark as read automatically when opening detail
    if (!notif.read) {
      setNotifications((prev) =>
        prev.map((n) => (n.id === notif.id ? { ...n, read: true } : n))
      );
    }
    setSelectedNotif({ ...notif, read: true });
  };

  const handleResetFilters = () => {
    setSearchQuery("");
    setTypeFilter("all");
    setStatusFilter("all");
    setTimeFilter("today");
    setCurrentPage(1);
    showToast("Notification filters reset.");
  };

  // Export PDF Report Generator
  const handleExportPDF = () => {
    const printWin = window.open("", "_blank");
    if (!printWin) {
      showToast("✕ Pop-up blocked. Please allow pop-ups to export PDF.");
      return;
    }

    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Mediflow General Hospital — Notification Activity Log</title>
          <style>
            body { font-family: system-ui, -apple-system, sans-serif; color: #0f172a; padding: 30px; margin: 0; }
            .header { border-bottom: 2px solid #071b34; padding-bottom: 15px; margin-bottom: 20px; display: flex; justify-content: space-between; align-items: flex-end; }
            .hospital-title { font-size: 24px; font-weight: 800; color: #071b34; margin: 0; }
            .report-title { font-size: 14px; font-weight: 700; color: #1677ff; text-transform: uppercase; letter-spacing: 1px; margin-top: 4px; }
            .meta { font-size: 11px; color: #64748b; text-align: right; }
            .summary-cards { display: flex; gap: 12px; margin-bottom: 24px; }
            .card { flex: 1; padding: 12px; border-radius: 8px; border: 1px solid #cbd5e1; background: #f8fafc; }
            .card-title { font-size: 10px; font-weight: 700; text-transform: uppercase; color: #475569; }
            .card-val { font-size: 20px; font-weight: 800; margin-top: 4px; }
            table { width: 100%; border-collapse: collapse; margin-top: 10px; font-size: 12px; }
            th { background: #071b34; color: white; padding: 8px 12px; text-align: left; font-size: 11px; text-transform: uppercase; }
            td { padding: 10px 12px; border-bottom: 1px solid #e2e8f0; }
            .badge { display: inline-block; padding: 2px 6px; border-radius: 4px; font-size: 10px; font-weight: 700; text-transform: uppercase; }
            .critical { background: #ffe4e6; color: #e11d48; }
            .unread { font-weight: bold; color: #1677ff; }
            .footer { margin-top: 30px; border-top: 1px solid #e2e8f0; pt: 10px; font-size: 10px; color: #94a3b8; text-align: center; }
          </style>
        </head>
        <body>
          <div class="header">
            <div>
              <h1 class="hospital-title">Mediflow General Hospital</h1>
              <div class="report-title">Notification & Operational Event Log</div>
            </div>
            <div class="meta">
              <div>Generated: ${new Date().toLocaleString()}</div>
              <div>Applied Filters: Type (${typeFilter}), Status (${statusFilter})</div>
            </div>
          </div>

          <div class="summary-cards">
            <div class="card" style="border-left: 4px solid #1677ff;">
              <div class="card-title">Unread</div>
              <div class="card-val" style="color: #1677ff;">${unreadCount}</div>
            </div>
            <div class="card" style="border-left: 4px solid #e11d48;">
              <div class="card-title">Critical</div>
              <div class="card-val" style="color: #e11d48;">${criticalCount}</div>
            </div>
            <div class="card" style="border-left: 4px solid #0284c7;">
              <div class="card-title">Operational</div>
              <div class="card-val" style="color: #0284c7;">${operationalCount}</div>
            </div>
            <div class="card" style="border-left: 4px solid #64748b;">
              <div class="card-title">System</div>
              <div class="card-val" style="color: #64748b;">${systemCount}</div>
            </div>
          </div>

          <table>
            <thead>
              <tr>
                <th>Type</th>
                <th>Notification Title</th>
                <th>Department</th>
                <th>Timestamp</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${filteredNotifications
                .map(
                  (n) => `
                <tr>
                  <td><span class="badge ${n.type === "critical" ? "critical" : ""}">${n.type}</span></td>
                  <td><b>${n.title}</b><br/><span style="color:#64748b; font-size:10px;">${n.description}</span></td>
                  <td>${n.department}</td>
                  <td>${n.timestamp}</td>
                  <td class="${!n.read ? "unread" : ""}">${n.read ? "Read" : "UNREAD"}</td>
                </tr>
              `
                )
                .join("")}
            </tbody>
          </table>

          <div class="footer">
            Confidential Healthcare Operational Document — Mediflow General Hospital Notification Center
          </div>

          <script>
            window.onload = function() {
              window.print();
            };
          </script>
        </body>
      </html>
    `;

    printWin.document.open();
    printWin.document.write(htmlContent);
    printWin.document.close();
    showToast("✓ Notification PDF report generated.");
  };

  const getNotifIcon = (type: string) => {
    switch (type) {
      case "critical":
        return "🔴";
      case "ot":
        return "🔵";
      case "patient":
        return "🟠";
      case "cssd":
        return "🟣";
      case "operational":
        return "🟢";
      default:
        return "⚙️";
    }
  };

  return (
    <div className="space-y-8 max-w-[1400px] mx-auto font-sans select-none pb-24 text-slate-800 dark:text-slate-100">
      
      {/* Toast Notification Banner */}
      {toastMessage && (
        <div className="fixed top-20 right-6 z-[70] px-4 py-3 rounded-2xl bg-[#071B34] text-white font-bold text-xs shadow-2xl border border-cyan-400/40 flex items-center space-x-2.5 animate-in slide-in-from-top-4 duration-200">
          <span className="w-5 h-5 rounded-full bg-cyan-500/20 text-cyan-400 flex items-center justify-center text-xs">✓</span>
          <span>{toastMessage}</span>
        </div>
      )}

      {/* HEADER SECTION */}
      <div className="p-6 sm:p-8 rounded-3xl bg-[#071B34] text-white border border-white/15 shadow-[0_20px_50px_rgba(0,0,0,0.35)] flex flex-col md:flex-row items-start md:items-center justify-between gap-6 relative overflow-hidden">
        <div className="absolute -right-16 -top-16 w-64 h-64 rounded-full bg-cyan-500/10 blur-3xl pointer-events-none" />

        <div className="space-y-2 z-10">
          <div className="text-xs font-semibold text-cyan-400 uppercase tracking-widest">
            Mediflow General Hospital · Notification Center
          </div>
          <h1 className="text-2xl sm:text-3xl lg:text-4xl font-extrabold tracking-tight text-white">
            Notifications
          </h1>
          <p className="text-xs sm:text-sm text-slate-300 max-w-2xl font-normal leading-relaxed">
            Stay informed about hospital operations, alerts and workflow events across Mediflow General Hospital.
          </p>

          <div className="inline-flex items-center space-x-2 text-[11px] font-bold text-cyan-400 pt-1">
            <span className="w-2.5 h-2.5 rounded-full bg-cyan-400 animate-pulse shadow-[0_0_8px_#18D8E8]" />
            <span>● Live · {notifications.length} notifications · {unreadCount} unread</span>
          </div>
        </div>

        {/* Top Right Controls */}
        <div className="flex items-center space-x-3 z-10 w-full md:w-auto shrink-0">
          <button
            type="button"
            onClick={handleMarkAllRead}
            className="flex-1 md:flex-initial px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 border border-white/20 text-white font-semibold text-xs transition-all cursor-pointer hover:shadow-md active:scale-95"
          >
            Mark All as Read
          </button>
          
          <Link
            href="/settings"
            className="flex-1 md:flex-initial px-4 py-2.5 rounded-xl bg-white/10 hover:bg-white/15 border border-white/20 text-white font-semibold text-xs transition-all text-center cursor-pointer hover:shadow-md active:scale-95"
          >
            Notification Settings
          </Link>

          <button
            type="button"
            onClick={handleExportPDF}
            className="flex-1 md:flex-initial px-5 py-2.5 rounded-xl bg-gradient-to-r from-blue-600 via-blue-500 to-cyan-500 hover:from-blue-500 hover:to-cyan-400 text-white font-bold text-xs shadow-[0_4px_25px_rgba(22,119,255,0.4)] transition-all cursor-pointer active:scale-95"
          >
            Export PDF
          </button>
        </div>
      </div>

      {/* NOTIFICATION SUMMARY CARDS */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-5">
        {/* UNREAD */}
        <div
          onClick={() => setStatusFilter(statusFilter === "unread" ? "all" : "unread")}
          className="p-5 rounded-3xl bg-white dark:bg-[#0B2545] border-l-4 border-l-blue-600 border border-slate-200 dark:border-white/10 shadow-xs hover:shadow-md hover:-translate-y-1 transition-all cursor-pointer group"
        >
          <div className="flex justify-between items-start">
            <span className="text-xs font-extrabold text-blue-600 dark:text-cyan-400 uppercase tracking-wider">Unread</span>
            <span className="p-2 rounded-xl bg-blue-100 dark:bg-blue-950 text-blue-600 text-base group-hover:scale-110 transition-transform">📬</span>
          </div>
          <div className="text-3xl font-extrabold font-mono text-slate-900 dark:text-white mt-2">
            {unreadCount}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1">Pending review</p>
        </div>

        {/* CRITICAL */}
        <div
          onClick={() => setTypeFilter(typeFilter === "critical" ? "all" : "critical")}
          className="p-5 rounded-3xl bg-white dark:bg-[#0B2545] border-l-4 border-l-rose-500 border border-slate-200 dark:border-white/10 shadow-xs hover:shadow-md hover:-translate-y-1 transition-all cursor-pointer group"
        >
          <div className="flex justify-between items-start">
            <span className="text-xs font-extrabold text-rose-600 dark:text-rose-400 uppercase tracking-wider">Critical</span>
            <span className="p-2 rounded-xl bg-rose-100 dark:bg-rose-950 text-rose-600 text-base group-hover:scale-110 transition-transform">🚨</span>
          </div>
          <div className="text-3xl font-extrabold font-mono text-slate-900 dark:text-white mt-2">
            {criticalCount}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1">Emergency clinical items</p>
        </div>

        {/* OPERATIONAL */}
        <div
          onClick={() => setTypeFilter(typeFilter === "operational" ? "all" : "operational")}
          className="p-5 rounded-3xl bg-white dark:bg-[#0B2545] border-l-4 border-l-cyan-500 border border-slate-200 dark:border-white/10 shadow-xs hover:shadow-md hover:-translate-y-1 transition-all cursor-pointer group"
        >
          <div className="flex justify-between items-start">
            <span className="text-xs font-extrabold text-cyan-600 dark:text-cyan-400 uppercase tracking-wider">Operational</span>
            <span className="p-2 rounded-xl bg-cyan-100 dark:bg-cyan-950 text-cyan-600 text-base group-hover:scale-110 transition-transform">⚡</span>
          </div>
          <div className="text-3xl font-extrabold font-mono text-slate-900 dark:text-white mt-2">
            {operationalCount}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1">OT, Ward & CSSD workflow</p>
        </div>

        {/* SYSTEM */}
        <div
          onClick={() => setTypeFilter(typeFilter === "system" ? "all" : "system")}
          className="p-5 rounded-3xl bg-white dark:bg-[#0B2545] border-l-4 border-l-purple-500 border border-slate-200 dark:border-white/10 shadow-xs hover:shadow-md hover:-translate-y-1 transition-all cursor-pointer group"
        >
          <div className="flex justify-between items-start">
            <span className="text-xs font-extrabold text-purple-600 dark:text-purple-400 uppercase tracking-wider">System</span>
            <span className="p-2 rounded-xl bg-purple-100 dark:bg-purple-950 text-purple-600 text-base group-hover:scale-110 transition-transform">⚙️</span>
          </div>
          <div className="text-3xl font-extrabold font-mono text-slate-900 dark:text-white mt-2">
            {systemCount}
          </div>
          <p className="text-xs text-slate-500 dark:text-slate-400 font-medium mt-1">Administrative audit notices</p>
        </div>
      </div>

      {/* FILTER TOOLBAR */}
      <div className="p-6 rounded-3xl bg-white dark:bg-[#0B2545] border border-slate-200 dark:border-white/10 shadow-xs space-y-4">
        <div className="flex flex-col lg:flex-row items-stretch lg:items-center justify-between gap-4">
          
          {/* Search Input */}
          <div className="relative flex-1 min-w-[260px]">
            <span className="absolute left-3.5 top-3 text-slate-400 text-sm">🔍</span>
            <input
              type="text"
              placeholder="Search notifications..."
              value={searchQuery}
              onChange={(e) => {
                setSearchQuery(e.target.value);
                setCurrentPage(1);
              }}
              className="w-full pl-10 pr-4 py-2.5 text-xs font-semibold rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white focus:outline-none focus:ring-2 focus:ring-blue-500"
            />
          </div>

          {/* Filters Grid */}
          <div className="flex flex-wrap items-center gap-3 text-xs font-semibold">
            {/* Type */}
            <div>
              <select
                value={typeFilter}
                onChange={(e) => {
                  setTypeFilter(e.target.value);
                  setCurrentPage(1);
                }}
                className="px-3 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-bold cursor-pointer"
              >
                <option value="all">Type: All</option>
                <option value="critical">Critical</option>
                <option value="operational">Operational</option>
                <option value="patient">Patient</option>
                <option value="ot">OT</option>
                <option value="cssd">CSSD</option>
                <option value="system">System</option>
              </select>
            </div>

            {/* Status */}
            <div>
              <select
                value={statusFilter}
                onChange={(e) => {
                  setStatusFilter(e.target.value);
                  setCurrentPage(1);
                }}
                className="px-3 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-bold cursor-pointer"
              >
                <option value="all">Status: All</option>
                <option value="unread">Unread</option>
                <option value="read">Read</option>
              </select>
            </div>

            {/* Time */}
            <div>
              <select
                value={timeFilter}
                onChange={(e) => setTimeFilter(e.target.value)}
                className="px-3 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 text-slate-900 dark:text-white font-bold cursor-pointer"
              >
                <option value="today">Today</option>
                <option value="7d">7 Days</option>
                <option value="30d">30 Days</option>
              </select>
            </div>

            {/* Reset */}
            <button
              type="button"
              onClick={handleResetFilters}
              className="px-3.5 py-2.5 rounded-xl bg-slate-200 dark:bg-slate-700 hover:bg-slate-300 dark:hover:bg-slate-600 text-slate-700 dark:text-slate-200 font-bold transition-colors cursor-pointer"
            >
              Reset Filters
            </button>
          </div>
        </div>
      </div>

      {/* NOTIFICATION FEED LIST */}
      <div className="bg-white dark:bg-[#0B2545] rounded-3xl border border-slate-200 dark:border-white/10 shadow-xs overflow-hidden divide-y divide-slate-100 dark:divide-slate-800">
        {paginatedNotifications.length === 0 ? (
          <div className="p-12 text-center text-slate-500 font-bold text-xs">
            No matching notifications found for applied filter parameters.
          </div>
        ) : (
          paginatedNotifications.map((notif) => {
            const isUnread = !notif.read;
            return (
              <div
                key={notif.id}
                onClick={() => handleOpenDetail(notif)}
                className={`p-5 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-4 transition-all cursor-pointer border-l-4 ${
                  isUnread
                    ? "bg-[#f7faff] dark:bg-slate-800/80 border-l-blue-600 font-semibold"
                    : "bg-white dark:bg-[#0B2545] border-l-transparent hover:bg-slate-50 dark:hover:bg-slate-800/40"
                }`}
              >
                {/* Left Side: Icon & Title/Description */}
                <div className="flex items-start space-x-4">
                  <div className="w-10 h-10 rounded-2xl bg-slate-100 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 flex items-center justify-center text-lg shrink-0">
                    {getNotifIcon(notif.type)}
                  </div>

                  <div className="space-y-1">
                    <div className="flex items-center space-x-2.5">
                      <h3 className="font-extrabold text-sm text-slate-900 dark:text-white hover:text-blue-600 dark:hover:text-cyan-400 transition-colors">
                        {notif.title}
                      </h3>
                      {isUnread && (
                        <span className="w-2.5 h-2.5 rounded-full bg-blue-600 shadow-[0_0_8px_#1677FF] shrink-0" />
                      )}
                    </div>
                    
                    <p className="text-xs text-slate-600 dark:text-slate-300 leading-relaxed max-w-2xl font-normal">
                      {notif.description}
                    </p>

                    <div className="flex items-center space-x-3 text-[11px] font-semibold text-slate-500 dark:text-slate-400 pt-0.5">
                      <span className="px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-bold">
                        {notif.department}
                      </span>
                      <span>·</span>
                      <span>{notif.timestamp}</span>
                      {notif.entityId && (
                        <>
                          <span>·</span>
                          <span className="font-mono text-cyan-600 dark:text-cyan-400">{notif.entityId}</span>
                        </>
                      )}
                    </div>
                  </div>
                </div>

                {/* Right Side: Action Button & Toggle Read */}
                <div className="flex items-center space-x-3 self-end sm:self-center shrink-0" onClick={(e) => e.stopPropagation()}>
                  <Link
                    href={notif.actionHref}
                    className="px-4 py-2 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold text-xs shadow-xs transition-all cursor-pointer"
                  >
                    {notif.actionText}
                  </Link>

                  <button
                    type="button"
                    onClick={(e) => handleToggleRead(notif.id, e)}
                    className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-300 hover:bg-slate-200 text-xs font-bold cursor-pointer"
                    title={isUnread ? "Mark as Read" : "Mark as Unread"}
                  >
                    {isUnread ? "✓ Read" : "✉ Unread"}
                  </button>

                  <button
                    type="button"
                    onClick={(e) => handleDeleteNotif(notif.id, e)}
                    className="p-2 rounded-xl bg-rose-50 dark:bg-rose-950 text-rose-600 hover:bg-rose-100 text-xs font-bold cursor-pointer"
                    title="Delete Notification"
                  >
                    ✕
                  </button>
                </div>
              </div>
            );
          })
        )}

        {/* PAGINATION FOOTER */}
        <div className="p-4 border-t border-slate-200 dark:border-slate-800 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs font-bold text-slate-600 dark:text-slate-400">
          <div className="flex items-center space-x-3">
            <span>Show notifications per page:</span>
            <select
              value={pageSize}
              onChange={(e) => {
                setPageSize(Number(e.target.value));
                setCurrentPage(1);
              }}
              className="px-2.5 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 bg-slate-50 dark:bg-slate-800 font-bold"
            >
              <option value={10}>10</option>
              <option value={25}>25</option>
              <option value={50}>50</option>
            </select>
          </div>

          <div>
            Showing {filteredNotifications.length > 0 ? startIndex + 1 : 0}–
            {Math.min(startIndex + pageSize, filteredNotifications.length)} of {filteredNotifications.length} items
          </div>

          <div className="flex items-center space-x-1">
            <button
              type="button"
              disabled={safeCurrentPage <= 1}
              onClick={() => setCurrentPage((p) => Math.max(1, p - 1))}
              className="px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 disabled:opacity-40 cursor-pointer"
            >
              Previous
            </button>

            {Array.from({ length: totalPages }, (_, i) => i + 1).map((pg) => (
              <button
                key={pg}
                type="button"
                onClick={() => setCurrentPage(pg)}
                className={`w-8 h-8 rounded-lg font-bold transition-all cursor-pointer ${
                  pg === safeCurrentPage
                    ? "bg-blue-600 text-white"
                    : "hover:bg-slate-100 dark:hover:bg-slate-800 text-slate-700 dark:text-slate-300"
                }`}
              >
                {pg}
              </button>
            ))}

            <button
              type="button"
              disabled={safeCurrentPage >= totalPages}
              onClick={() => setCurrentPage((p) => Math.min(totalPages, p + 1))}
              className="px-3 py-1.5 rounded-lg border border-slate-200 dark:border-slate-700 hover:bg-slate-100 disabled:opacity-40 cursor-pointer"
            >
              Next
            </button>
          </div>
        </div>

      </div>

      {/* NOTIFICATION DETAIL SIDE DRAWER / MODAL */}
      {selectedNotif && (
        <div className="fixed inset-0 z-[80] flex items-center justify-end bg-slate-900/60 backdrop-blur-xs p-4 animate-in fade-in duration-200">
          <div className="w-full max-w-lg h-full max-h-[90vh] bg-white dark:bg-slate-900 rounded-3xl shadow-2xl p-6 sm:p-8 border border-slate-200 dark:border-slate-800 flex flex-col justify-between overflow-y-auto space-y-6">
            
            <div className="space-y-6">
              {/* Drawer Header */}
              <div className="flex justify-between items-start border-b border-slate-100 dark:border-slate-800 pb-4">
                <div>
                  <div className="flex items-center space-x-2 mb-1">
                    <span className="text-xl">{getNotifIcon(selectedNotif.type)}</span>
                    <span className="px-2.5 py-0.5 rounded-full bg-blue-100 text-blue-700 dark:bg-blue-950 dark:text-blue-300 text-[10px] font-extrabold uppercase">
                      {selectedNotif.type}
                    </span>
                    <span className="text-xs font-mono text-slate-400">{selectedNotif.id}</span>
                  </div>
                  <h2 className="text-lg font-extrabold text-slate-900 dark:text-white tracking-tight">
                    {selectedNotif.title}
                  </h2>
                </div>

                <button
                  type="button"
                  onClick={() => setSelectedNotif(null)}
                  className="text-slate-400 hover:text-slate-600 dark:hover:text-white text-xl font-bold"
                >
                  ✕
                </button>
              </div>

              {/* Notification Metadata */}
              <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/60 border border-slate-200 dark:border-slate-700 space-y-3 text-xs">
                <p className="text-slate-800 dark:text-slate-200 font-medium leading-relaxed">
                  {selectedNotif.description}
                </p>

                <div className="grid grid-cols-2 gap-3 pt-2 text-[11px] font-semibold text-slate-600 dark:text-slate-400 border-t border-slate-200 dark:border-slate-700">
                  <div>Department: <b className="text-slate-900 dark:text-white">{selectedNotif.department}</b></div>
                  <div>Timestamp: <b className="text-slate-900 dark:text-white">{selectedNotif.timestamp}</b></div>
                  <div>Read Status: <b className={selectedNotif.read ? "text-emerald-600" : "text-blue-600"}>{selectedNotif.read ? "Read" : "Unread"}</b></div>
                  <div>Entity ID: <b className="text-cyan-600 font-mono">{selectedNotif.entityId || "N/A"}</b></div>
                </div>
              </div>

              {/* Event Timeline */}
              {selectedNotif.timeline && selectedNotif.timeline.length > 0 && (
                <div className="space-y-2.5 text-xs">
                  <h3 className="font-extrabold text-slate-900 dark:text-white">Event Audit Log</h3>
                  <div className="space-y-2 pl-2 border-l-2 border-slate-200 dark:border-slate-700">
                    {selectedNotif.timeline.map((item, idx) => (
                      <div key={idx} className="relative pl-4">
                        <span className="absolute -left-[9px] top-1 w-2 h-2 rounded-full bg-cyan-500" />
                        <span className="font-mono text-[10px] text-slate-400">{item.time}</span>
                        <p className="font-medium text-slate-800 dark:text-slate-200">{item.event}</p>
                      </div>
                    ))}
                  </div>
                </div>
              )}
            </div>

            {/* Footer Action Controls */}
            <div className="flex justify-end space-x-3 pt-4 border-t border-slate-100 dark:border-slate-800 text-xs font-bold">
              <button
                type="button"
                onClick={(e) => handleDeleteNotif(selectedNotif.id, e)}
                className="px-4 py-2.5 rounded-xl bg-rose-50 text-rose-600 hover:bg-rose-100 cursor-pointer"
              >
                Delete
              </button>

              <button
                type="button"
                onClick={(e) => handleToggleRead(selectedNotif.id, e)}
                className="px-4 py-2.5 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-800 dark:text-slate-200 hover:bg-slate-200 cursor-pointer"
              >
                {selectedNotif.read ? "Mark Unread" : "Mark Read"}
              </button>

              <Link
                href={selectedNotif.actionHref}
                className="px-5 py-2.5 rounded-xl bg-blue-600 hover:bg-blue-500 text-white shadow-md cursor-pointer text-center"
              >
                Open Related Item →
              </Link>
            </div>

          </div>
        </div>
      )}

    </div>
  );
}
